{
	"Server": {
		"TargetFazIp": "172.16.179.19",
		"FgtSn": "FGT60C0000000000",
		"EmsSn": "",
		"FctIp": "172.16.79.1",
		"FctSn": "FCT0001234567890",
		"FctCount": "1",
		"UseSSL": "y"
	},
	"FortiClient": {
		"ElogFields": {
			"logver":["2"],
			"utmaction": ["blocked", "passthrough"],
			"utmevent": ["webfilter"],
			"fctver": ["5.4.1.0856", "5.4.1.0840"],
            "os": ["Microsoft Windows Server 2008 R2 Standard Edition, 64-bit Service Pack 1 (build 7601)",
                   "Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)"],
			"user": ["Administrator", "tester", "Henry-PC"],
			"level": ["info", "warning", "critical"],
			"clientfeature": ["system", "av", "endpoint", "sslvpn", "update"],
			"devicemac":["00-1b-fc-ee-81-25", "00-1b-f3-ee-81-25"],
			"id": ["96837","39484"],
			"msg": ["\"Endpoint Control Status changed - Compliant\"", "\"FortiShield blocked application: C:\\\\Windows\\\\regedit.exe from modifying: \\\\REGISTRY\\\\MACHINE\\\\SOFTWARE\\\\Wow6432Node\\\\Fortinet\\\\FortiClient\\\\FA_DBLOG\\\\log_upload_freq_minutes\""],
            "epmgmtst":["blocked", "quarantined", "unblocked", "unquarantined"],
            "eponlinest":["regonline", "regoffline"],
            "epplace":["onnet", "offnet"]
		},
		"TlogFields": {
			"logver": ["2"],
            "type": ["traffic"],
            "utmevent": ["webfilter", "appfirewall"],
			"level": ["info", "warning"],
			"user": ["Administrator", "tester"],
			"sessionid": ["712873912", "329832", "21983103"],
			"srcname": ["iexplore.exe", "skype.exe", "chrome.exe", "GoogleUpdate.exe"],
			"srcip": ["172.16.198.12", "172.16.93.12"],
			"srcport": ["283", "12312", "443"],
			"direction": ["outbound", "inbound"],
			"remoteip": ["183.123.43.1","8.8.8.8"],
			"remotename": ["www.wtp101.com", "pixels.sbal4kp.com"],
			"remoteport":["80", "8080", "3323"],
			"url":["/index.html", "/query?adfa"],
			"proto": ["http","https","smtp"],
			"rcvdbyte": ["0","2000"],
			"sendbyte": ["0", "3000"],
			"utmaction": ["blocked", "passthrough"],
			"threat": ["Security Risk:Malicious Websites"],
            "srcproduct": ["Google Update", "Skype"],
			"fctver": ["5.4.1.0856", "5.4.1.0840"],
            "os": ["Microsoft Windows Server 2008 R2 Standard Edition, 64-bit Service Pack 1 (build 7601)",
                   "Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)"],
            "hostname": ["Henry-PC", "WIN2008-Server"]
		},
		"NlogFields": {
			"logver": ["2"],
			"level": ["info", "warning"],
			"clientfeature": ["vulnerabilityscan"],
			"user": ["Administrator", "tester"],
			"status": ["started"],
			"vulncat": ["Windows", "Web Client", "Operating System"],
			"vulncvss": ["9.3", "7.2", "2.3", "5.4"],
			"vulnengine": ["eng_ver=1.373"],
			"vulnid": ["31794", "31608", "31601", "26284", "26256", "26255", "26251",
                       "32042", "32054", "32064", "32075", "32175", "32096"],
			"vulnname": ["MS.NET.Framework.Array.Offset.Vulnerability.MS11-039",
                         "Microsoft.Cumulative.Update.for.Internet.Explorer.MS13-037",
                         "Security Update for Netlogon",
                         "Security Update for Microsoft Graphics Component",
                         "Security vulnerabilities fixed in Firefox 50"],
			"vulnref": ["www.fortinet.com/ids/VID37066", "www.fortinet.com/ids/VID29277"],
			"vulnseverity": ["Critical", "High", "Medium"],
            "vd":["root", "vdom1", "vdom2", "vdom3", "vdom4", "vdom5"],
			"fctver": ["5.4.1.0856", "5.4.1.0840"],
            "os": ["Microsoft Windows Server 2008 R2 Standard Edition, 64-bit Service Pack 1 (build 7601)",
                   "Microsoft Windows 7 Professional Edition, 64-bit Service Pack 1 (build 7601)"]
        },
		"Interval": 10,
		"LogCount": 100
	}
}
